server:
  port: 8084

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/aandrezz40/microservicionV.1
          default-label: config-server     # o la rama real de tu repo
          search-paths: config-data
