server:
  port: 9090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuario**

        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/api/carro/**

        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/api/moto/**

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka